name: Build package and push

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug:
        description: Sets "NODE_ENV" to "debug".
        default: false
        type: boolean
      type:
        description: Sets semantic version update type.
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-package-and-push:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - uses: thaibault/build-package-push-action@main
        id: build-package-and-push
        with:
          debug: ${{ inputs.debug || '' }}
          type: ${{ inputs.type || 'patch' }}

      - name: print
        run: echo Newly determined version is \"${{ steps.build-package-and-push.outputs.version }}\".
        shell: bash

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          tag: ${{ steps.build-package-and-push.outputs.version }}
