name: Deploy documentation website
run-name: Deploy documentation website

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug:
        description: Sets "NODE_ENV" to "debug".
        default: false
        type: boolean

jobs:
  main:
    runs-on: ubuntu-latest
    container: node:lts

    steps:
      - uses: thaibault/documentation-website@main
        with:
          debug: ${{ inputs.debug || '' }}
